
- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.25.2/prometheus-2.25.2.linux-armv7.tar.gz
    dest: /tmp
    checksum: sha256:d4883c2b3d7ce0272671650b6c5b5b9b6b71c272f8b9bbe9a1d8fa295a656a6a 


- name: Create Prometheus folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus
    state: directory
    mode: '0777'

- name: Extract Prometheus
  become: yes
  unarchive:
     src: /tmp/prometheus-2.25.2.linux-armv7.tar.gz
     dest: /usr/bin/prometheus
     remote_src: yes

- name: Create Prometheus Service File
  become: yes
  file:
      path: /etc/systemd/system/prometheus.service
      state: touch

- name: Create Prometheus data folder in opt
  become: yes
  file:
    path: /usr/bin/prometheus/prometheus-2.25.2.linux-armv7/data
    state: directory
    mode: '0777'

- name: Edit Prometheus Service File
  become: yes
  blockinfile:
      path: /etc/systemd/system/prometheus.service
      marker: ""
      block: |
        [Unit]
        Description=Prometheus Server
        Documentation=https://prometheus.io/docs/introduction/overview/
        After=network-online.target

        [Service]
        User=pi
        Restart=on-failure

        ExecStart=/usr/bin/prometheus/prometheus-2.25.2.linux-armv7/prometheus \
        --config.file=/usr/bin/prometheus/prometheus-2.25.2.linux-armv7/prometheus.yml \
        --storage.tsdb.path=/usr/bin/prometheus/prometheus-2.25.2.linux-armv7/data

        [Install]
        WantedBy=multi-user.target

- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: Start Prometheus service
  become: yes
  service:
    name: prometheus
    enabled: yes
    state: started